name: Main Branch Pipeline
on:
  push:
    branches:
      - main
run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo
      

  tests:
    runs-on: self-hosted
    needs: build  # needs like depends on
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

  dev:
    runs-on: self-hosted
    needs: tests
    environment: dev # created an 'Environment' in github settings of roboshop-cart project and for each env , i give the approval rights.
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

  qa:
    runs-on: self-hosted
    needs: dev
    environment: qa
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

  UAT:
    runs-on: self-hosted
    needs: qa
    environment: UAT
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo
          

  prod:
    runs-on: self-hosted
    needs: UAT
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo
          

#run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }} --> THis is will give coomit id + comments in pipiline
#