name: Cart CI Pipeline
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo
      

  tests:
    runs-on: self-hosted
    needs: build  # needs like depends on
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

  dev:
    runs-on: self-hosted
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

  qa:
    runs-on: self-hosted
    needs: dev
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

  UAT:
    runs-on: self-hosted
    needs: qa
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo
          

  prod:
    runs-on: self-hosted
    needs: UAT
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo